### ISSUE TITLE
Boulder Trap - Blocked way 44-g

### ISSUE THREAD

**Issue by Bloodwyn2** [ekunuke/vagante_issues#101]
Boulder Trap - Pushed block into square without realizing it would block way down.
Saved with Debug info on.
![44-g boulder trap - unable to complete lvl](https://cloud.githubusercontent.com/assets/16508793/15988894/268771e4-3016-11e6-81cc-9bbf5b2e3432.jpg)

**Comment by phantom-voltage** [comment]
I have a similar problem, found in 47b.

Two boulders were stacked together, and a slime pushed out the bottom one, killing the slime and subsequently blocking the exit.

I have a screenshot with the debug info.

![Stuck in Catacombs](http://images.akamai.steamusercontent.com/ugc/264969216701235654/3076BB264F3935F384489BAC231E8A358C20045B/)

**Comment by k6l2** [comment]
As of build 48, these issues should be resolved.

**Comment by phantom-voltage** [comment]
Awesome stuff!
