### ISSUE TITLE
Keyboard not recognized at all [WIN10]

### ISSUE THREAD

**Issue by zeroZshadow** [ekunuke/vagante_issues#103]
As the title says, none of my keyboard input works in the game, at all.
Under controls settings, Player1 is set to Enabled and Keyboard.

Attempting to rebind any keys will fail.
Using defaults, and then playing a single player games will make it impossible to play, as I the spacebar is not recognized at all.

This has been tested with 2 different keyboard.
The steam overlay (bound to ctrl + ) does work.

**Comment by ekunuke** [comment]
Could you verify your game version please?

Does anything change after unplugging other USB gamepads/peripherals?

**Comment by zeroZshadow** [comment]
I've tried this on both the stable and beta branch. And using an alternative keyboard.
I do not have a gamepad plugged in.

A small side note, is that since a week or so, I'm noticing keyboard issues in other games as well.
But this usually just 1 key not working, left shift, while writing capital letters using that left shift still work.
This is the only game where NO input works at all.

If there is anything I can do to help, test, debug logs, etc. Just ask.

**Comment by ekunuke** [comment]
What kind of keyboard are you using? Also, would you mind posting your log file? (only the first 100 or so lines are necessary).

**Comment by zeroZshadow** [comment]
Roccat MK Glow

Here is the log
https://gist.github.com/zeroZshadow/7043c97ff47a8236b47de459a6e21050

I took the following steps:
- Started the game
- clicked new game
- hit space bar a few things, nothing happened
- closed to game by clicking the X top right

**Comment by zeroZshadow** [comment]
Would like to make the addition that the game does WORK with the steam controller (it just arrived, so I couldn't check with a controller before)
It's only the keyboard that doesn't seem to work.

**Comment by zeroZshadow** [comment]
It seems the issue was caused by "Synergy". A piece of software used to share mouse and keyboard with other devices on the network.
The issue has been reported, but currently still exists in the latest 1.7.6 build.

**Comment by ekunuke** [comment]
Thanks for the update, Martijn!

I've used Synergy in the past; it's good to know that such issues can happen.
