### ISSUE TITLE
Multiple Slime Bosses

### ISSUE THREAD

**Issue by mishapsi** [ekunuke/vagante_issues#105]
Encountered not one, not three, but two slime bosses on the slime floor

**Comment by ekunuke** [comment]
Not necessarily a bug; kyle put in a hardcoded 0.01% chance for any slime to become a boss slime. So it's not infeasible that out of all the slimes in the level, one of them became another boss.

Whether or not this is something we want in the game, is another q..

**Comment by k6l2** [comment]
I guess it's probably not a good idea to have > 1 per level?..
