### ISSUE TITLE
Plant eats the Door. Patch46c

### ISSUE THREAD

**Issue by RemediaV** [ekunuke/vagante_issues#106]
Hey guys,
Found a little bug in Patch 46c. A plant spawned next to the level exit door, and when it tried to eat me it ate the door instead like it would a Spriggan or box. When I killed the plant the door graphic stayed where the plant was but I couldn't reach it. I found out after a few seconds that just the graphic of the door had moved. and the level exit was still where the door WAS. 

Its hard to explain but I have it on video here: https://youtu.be/foPiDBJQnHg?t=46m20s
It happens at 46:20 and I end up going through the door that isn't there around 47:40  in this video.

Hope this helps!!

**Comment by k6l2** [comment]
Apparently ekun already fixed this? _shrug emoji_
