### ISSUE TITLE
[Windows] Evil familiar causes weird behavior on when idling on a ledge

### ISSUE THREAD

**Issue by ghost** [ekunuke/vagante_issues#116]
I was holding on to a ledge when the evil familiar's raise-into-air behavior triggered and I was lifted into the air, while still in the ledgegrab animation. I was stuck inside the wall above, as shown in the picture, and no action could get my character out of the wall.

![capture](https://cloud.githubusercontent.com/assets/3527169/17087009/e1b2e4be-51c5-11e6-9b85-e071c127d901.PNG)

**Comment by k6l2** [comment]
should be fixed next release
