### ISSUE TITLE
Platform release version mismatch

### ISSUE THREAD

**Issue by williamblevins** [ekunuke/vagante_issues#128]
Cross platform multiplayer broken due to Steam latest game version different between Windows and Linux. This isn't even a bug with the title, it is just a problem with release organization/consistency. Please fix.

**Comment by ekunuke** [comment]
Thanks for reporting this. There was a bug with our automated build system set up (Jenkins was not calling scripts with -ex) which made me overlook this.

Sorry for the inconvenience, let me know if you run into any additional issues.

**Comment by williamblevins** [comment]
Thanks!
