### ISSUE TITLE
"Permanent" stat buffs from potions not retained after loading savegame

### ISSUE THREAD

**Issue by awksie** [ekunuke/vagante_issues#132]
Issue: see topic.

How to reproduce: Find some potions that add +1 to a given statistic. Tested with Fire Resistance and Poison Resistance. Defeat the level after drinking it and save your game. Then, resume your game and note that those stats are not increased.

Version: 54c

**Comment by k6l2** [comment]
Thanks for reporting.  Will be fixed next version.
