### ISSUE TITLE
Tele-frag death in multiplayer results in invisible player after revival

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#2]
>In multiplayer, occasionally when reviving a dead player, the dead player (skeleton) will respawn invisible. This is not the rogue ability, they are completely unrendered. Their attacks (fists and magic) are rendered, just not them.
>
>Things they cannot do:
>move
>pickup items
>jump
>fall (even if the floor is removed)
>
>Things they can do:
>attack
>turn left and right (visible by attack direction)
>take damage
>
>We believe it is caused by dying to a wall phase, and then reviving. Changing levels inbetween the >death and the revive seems to make no difference. We have repeated it only twice though.

[Link to post on forums](http://steamcommunity.com/app/323220/discussions/2/527274088404643589/)

**Comment by TheTeacheror** [comment]
Just a note, it is after the player revives with life water. Not while they are a skeleton. The skeleton itself works just fine.

**Comment by ekunuke** [comment]
Thanks for that, good point.
