### ISSUE TITLE
Move Oxygen indicator to above or around player

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#39]
Probably talk to Keo about this; we discussed potential ui options at one point i think

**Comment by inkhsutesou** [comment]
Aw ..  I hope this is an option as I prefer it not get in the way of the play area and rather it remain where I view all my other HP/MP etc

**Comment by ekunuke** [comment]
If we do this, we'd probably do our best to keep it unobtrusive.

**Comment by ekunuke** [comment]
This has already been added.
