### ISSUE TITLE
Coins dropped from Quest Fox heals more HP with "Coins seem to heal injuries"

### ISSUE THREAD

**Issue by inkhsutesou** [ekunuke/vagante_issues#41]
I have looped the game once.
I took a quest from a Quest Fox in the forest.
After stealing the item using wall phase
I leave the stage and go to the campfire
The quest fox is there.
I rest at the campfire and gain 10hp
I press up on the Quest Fox
The item is given (death protection amulet ?)
Some coins heal 5 and 3, I see the numbers.

Don't know if this is undesired behavior.

**Comment by ekunuke** [comment]
Each gold piece object doesn't necessarily represent one piece of gold; when large amounts of gold are dropped, a gold piece object may be worth larger amounts of gold.
