### ISSUE TITLE
Thief quest NPC crashes upon leaving intermission.

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#43]
http://steamcommunity.com/app/323220/discussions/2/492379159711092491/

**Comment by ethanlu** [comment]
Hey,

Attached is the saved game file that causes the crash. I had to change the extension to .txt so that github will accept it.

Thanks again!

[000.txt](https://github.com/ekunuke/vagante_issues/files/50436/000.txt)

**Comment by k10** [comment]
Awesome dude thanks, I'll be checking this out today.

**Comment by k10** [comment]
I figured out the problem, thanks a lot for helping out!

**Comment by ethanlu** [comment]
Happy to help and thanks for addressing it so quickly.  Will be looking forward to the next patch :)
