### ISSUE TITLE
Fox quest NPC crash

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#45]
Talking to fox in Ruins caused crash for a player
http://steamcommunity.com/app/323220/discussions/2/494631967660184153/

**Comment by k10** [comment]
This shouldn't be possible because the game should check to see if there is a shop in the level before setting the Thief to be a quest NPC in the first place...  Something very weird is going on here...

**Comment by k6l2** [comment]
I added an extra check in LevelGenerator just to make absolute sure that no shenanigans happens.. Hopefully this wont happen anymore??...
