### ISSUE TITLE
Goblin pathfinding glitchy

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#47]
Sometimes tries to jump through 1 thickness ceilings, spazes on boulder blocks too
http://steamcommunity.com/app/323220/discussions/2/494631967665912984/

**Comment by k10** [comment]
The steam post linked describes an issue completely unrelated to pathfinding, but yes, pathfinding is an issue.

**Comment by ekunuke** [comment]
This should be a lot better now.

Fixed
- LEAP_OVER causing issues where monsters would try to jump through solid blocks
- aggroTimer not doing what it's supposed to
- getting stuck on boulders
