### ISSUE TITLE
Teleport Scroll inside Between Level Area creates Soft-lock

### ISSUE THREAD

**Issue by ekunuke** [ekunuke/vagante_issues#5]
Using a teleport scroll inside the between level area (where the campfire is) and teleporting to the right side of the screen (where the game moves the character onward) will make it so the player cannot move in the next level, thus soft-locking the game.

from: http://steamcommunity.com/app/323220/discussions/2/523898291499218809/

**Comment by k10** [comment]
I can reproduce by using the teleport scroll as the player is walking to their sitting location at the campfire, and the teleport scroll places you at the transition zone.

**Comment by k10** [comment]
I fix it
