### ISSUE TITLE
Can't start game on SteamOS

### ISSUE THREAD

**Issue by binary132** [ekunuke/vagante_issues#51]
NVidia GTX 960, 8GB of ram, X4-860k CPU, booted into SteamOS, using steam controller and Steam beta client.

I click Play on the Steam menu for the game, it says "launching / preparing to launch Vagante", and then the screen blanks out for a brief moment before returning me to the game screen in Steam as though nothing had happened.

I've tried verifying the local content as well as uninstalling and reinstalling.  No luck yet.  Would really like to give this game a spin!

I'll see if I can dig up the logs if this is insufficient.

**Comment by thekidcrash** [comment]
I got the same on Ubuntu 14.04.3 LTS. Log:
> Game update: AppID 323220 "Vagante", ProcID 10580, IP 0.0.0.0:0
> ERROR: ld.so: object '/home/kidcrash/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/kidcrash/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/kidcrash/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Game removed: AppID 323220 "Vagante", ProcID 10580

uname -a
> Linux  3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ekunuke** [comment]
This looks related to: https://github.com/ValveSoftware/steam-for-linux/issues/3093

A couple of questions:
* Are your drivers up to date?
* Are you running a multiple monitor set up?
* Does disabling the steam overlay fix the problem, or change the log file at all?

**Comment by thekidcrash** [comment]
>Are your drivers up to date?
Yes
>Are you running a multiple monitor set up?
No
>rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
No such file or directory (and there is no ubuntuXX_YY dir in ~/.local/share/Steam/)

**Comment by ekunuke** [comment]
>How to disable steam overlay?

If you go to the Steam *Library* page, it's possible to right click on the game (Vagante) and go to properties.

From there, the *General* tab should have a tickbox for *Enable the Steam Overlay while in-game*

**Comment by thekidcrash** [comment]
doesn't work, same error

**Comment by ekunuke** [comment]
I installed SteamOS on my extra laptop the other day to figure out what the problem is.

I successfully got Vagante running on my machine, but I had to fix several dependency issues first (_libjpeg8_, _libudev0_, and _libxcb-image0_ specifically).

We're still fixing the steam download so it works right of the box, but if you wish to manually solve the issue in the meantime, installing the above listed packages should do the trick.

**Comment by akimbobandman** [comment]
I couldn't find libxcb-image0? And the other two have been replaced by other libs. Any help anyone? I'm new to Linux

**Comment by ekunuke** [comment]
Sorry for the delay, I've finally fixed this issue I think with Vagante v40c.

If you guys get a chance, please let me know if this fixes your startup issues.

**Comment by ghost** [comment]
@ekunuke I actually encountered this error for the first time when I updated my client about 2 days ago. I was able to launch every linux update since Feb 27, 2016 which is when I installed the game for the first time.

uname -a

> linux ex 4.1.18-1-lts _#_1 SMP Tue Feb 16 20:17:57 CET 2016 x86_64 GNU/Linux

**Comment by ghost** [comment]
I just received another update, and now the window appears as well as a loading screen, but I get a segfault when the bar reaches roughly the center of the screen.

**Comment by ghost** [comment]
Apparently a file failed to validate. I removed two configuration files as per the suggestions in a forum post (but I tried that only after I couldn't launch the game).

The game does work now. Thanks!

**Comment by akimbobandman** [comment]
Still can't launch in steamos. It does the same thing

**Comment by ghost** [comment]
The LD_PRELOAD errors are unrelated though, right? For everyone involved I think.

**Comment by akimbobandman** [comment]
I'm fairly new to Linux. My steam machine is my first real experience with it. All I know is that it's doing the same thing as it was before 40c

**Comment by ekunuke** [comment]
Sorry guys, we managed to fix the issue here but in doing so broke the game for some other Linux users. So we reverted the change.

I hope to be able to fix this soon though.

**Comment by sportpeppers** [comment]
I also have a steam machine and this game won't launch. Will there be a fix? It launches on my Ubuntu 15.10 system but not steamos. I don't play games on the Ubuntu desktop though just my steam machine.

**Comment by ghost** [comment]
Now it doesn't run for me again, ever since I switched to the open source Radeon drivers.

**Comment by ephja** [comment]
And now it works for me again, with version 43a.

**Comment by ghost** [comment]
I'm pretty sure it was related to the fact that steam uses old library versions this time.

**Comment by sportpeppers** [comment]
Still broken for me. Will it ever get fixed on steamos?

**Comment by sportpeppers** [comment]
Is this even being planned for a fix? Do you understand the problem? Is there something I can provide to help?

**Comment by ekunuke** [comment]
Sorry for the lack of updates. We've been busy with a lot of different things, but I'll dedicate time to figuring this out this week. 

The main issue I'm running into atm is that the steam-runtime (the package of libraries automatically included with a steam install) doesn't include the right version of one of the libraries we depend on. As we need to distribute a build that works on SteamOS as well as other Linux distros, I'm trying to figure out a universal solution.

**Comment by ekunuke** [comment]
I've gone ahead and tried creating a build that may have fixed the issue.
Please try downloading and running this: http://nukenine.com/files/linux-test.tar.gz
I believe Steam has to be running as well.

edit: If you have a non-SteamOS distro to test on, that would be helpful too.

**Comment by sportpeppers** [comment]
Thanks for looking at this!

I replaced the contents of my vagante folder with this and the game launches on steamos. My steam controller doesnt work though. It shows up in the settings so the game seems to know it's there, but i can't use any of the buttons on it (have to use a keyboard to navigate the menus). The only button on the steam controller that works while vagante is running is the steam button, which takes me to the big picture overlay menu... but I can't navigate it. All the buttons on the steam controller are stuck and inoperable until I close vagante.

I tried this on an ubuntu 15.10 machine and it worked fine. I dont have my steam controller connected there, but it worked perfectly with an xbox360 controller (I have not tried the xbox 360 controller on steamos with this package).

**Comment by ekunuke** [comment]
The SteamController issue seems to be a separate one, as it's been an issue on OSX as well. We'll tackle that after this is fully resolved.

We're releasing a new patch today; I'll try pushing the linux build with the SteamOS fix. After the build is public (Build 47), please let me know in this thread if it runs smoothly or still has issues.

**Comment by sportpeppers** [comment]
Build 47 launches perfectly on both my ubuntu 15.10 system and steamos. Thanks!!

What bug should i track for the steam controller issue? In general it seems Vagante's controller behavior is strange. For instance, when I disable a player (usually accidentally because i uncheck a box instead of going 'back' a menu), all controller input is entirely disabled even for BPM. This makes it tough to play the game on the couch since it's pretty easy to mess up the controls and not be able to recover without a keyboard. As an example, if I am using the xbox360 controller and accidentally switch to keyboard controls for player 1, i can't use BPM anymore (it is like it locks out the controller entirely) until I've closed vagante. Then usually Vagante remembers my config and I have to fix it before being able to use the controller again. This seems related to the steam controller issue, but I really dont know what I'm talking about. :)

**Comment by addict3d** [comment]
Just writing to say that Build 47 starts and runs successfully for me on steamos. Thanks!
