### ISSUE TITLE
fullscreen game = bluescreen

### ISSUE THREAD

**Issue by probablynotcereal** [ekunuke/vagante_issues#56]
whenever i try to play vagante in full screen i always bluescreen with a message saying PAGE_FAULT_IN_NONPAGED_AREA. I
 am running windows 10. This happens on both my laptop and my desktop so i dont think specifying hardware matters.

p.s. i had to rename the log file from log.log to log.txt to upload
[log.txt](https://github.com/ekunuke/vagante_issues/files/80584/log.txt)

**Comment by ekunuke** [comment]
I suspect this is a driver issue, as there isn't really a way for our game to directly cause a blue screen error.

Are all of your drivers up to date? Have you tried fullscreening using a different monitor? Tried playing without usb joysticks or gamepads connected?
