### ISSUE TITLE
Fullscreen not working in Linux

### ISSUE THREAD

**Issue by Lyle-Tafoya** [ekunuke/vagante_issues#57]
Summary: Fullscreen is not working correctly in Linux with Gnome3 as my desktop environment.

Expected Behavior: Game window should take up the entire screen

Actual Behavior: Window shares screen space with the Gnome3 task bar. While the window is the correct resolution, it does not fill the entire screen and the bottom extends beyond the screen.

**Comment by ekunuke** [comment]
The Linux next release will have true fullscreen windows, instead of borderless fullscreen windows.

I expect this should fix the problem, but please update this issue if not.
