### ISSUE TITLE
Merchant couldnt open door to retrieve purchase (video included)

### ISSUE THREAD

**Issue by bluechipps** [ekunuke/vagante_issues#58]
Not easily reproducible so here's a clip of it. Thanks!
[https://www.youtube.com/watch?v=ufchXmslD_k](https://www.youtube.com/watch?v=ufchXmslD_k)

**Comment by ekunuke** [comment]
Thanks for the vid!

**Comment by ekunuke** [comment]
I think this is just a floating point collision issue (where the door physical collision box extends past the trigger collision box). Fixed for next update..

**Comment by bluechipps** [comment]
Nice, glad it was a simple fix
