### ISSUE TITLE
Controller not rebindable on linux

### ISSUE THREAD

**Issue by Laeri** [ekunuke/vagante_issues#62]
Using XBox360 Controllers it is not possible to rebind any keys. Default buttons
seem to work but no axis work per default. Controllers have necessary drivers and work for other games (for example Broforce). Controller support is a really important feature in my opinion and I would be really glad if the linux support for that could be guaranteed.
The debug option shows for the left stick either 100 or -100.
Specs:
OS: Antergos
Kernel: x86_64 Linux 4.3.3-3-ARC
CPU: Intel Core i5-3317U CPU @ 2.6GHz
GPU: Mesa DRI Intel(R) Ivybridge Mobile

**Comment by ekunuke** [comment]
Laeri, are you sure it's the left stick that's stuck? 

We've recently had a similar report from a Windows player who has the same issue with their *right* stick.

**Comment by Laeri** [comment]
Ekunuke I'm sorry I might have not been clear enough. If i try to rebind any button/stick I can press any key/axis and nothing happens. So not only the left stick is the problem but every controller input.
By the way the game is amazing and fun to play!

**Comment by ekunuke** [comment]
Ah, what I meant by my comment was whether the Debug Option (that shows 100 or -100) was indeed for the left stick specifically, or just some unnamed axis.

**Comment by Laeri** [comment]
So this is the debug dialog which is displayed while rebinding:
Product 1817 / Vendor 1118
No press:
Axis Held 2 negative at position: -100
Axis Held 3 negative at position: -100
Moving left stick left/right:
Axis Held 0 negative at position -100/100 respectively
Moving left stick up/down
Axis Held 1 negative at position -100/100
Moving Right stick left/right
Axis Held 4 negative at position -100/100
Moving Right stick up/down
Axis Held 5 negative at position -100/100
While pressing any other keys the buttons 0-5 are displayed.
What is a bit strange when pressing LT/RT no button code is displayed but the Axis value of 2/3 change to a very high number and it flickers momentarily.

**Comment by ekunuke** [comment]
Thanks for the details, Laeri. That was exactly what I needed. I'm looking into this now.
