### ISSUE TITLE
Shockwave doesn't turn into Mana Orb

### ISSUE THREAD

**Issue by mishapsi** [ekunuke/vagante_issues#71]
Shockwave won't orb

**Comment by k6l2** [comment]
There currently are no other "earth element" spells, so the behavior can't be added yet.  Should there be able to make earth orbs even though it's the only spell of that element? Should other spells be made/added that are "earth element"?

**Comment by k6l2** [comment]
Unless mana orbs come back for some reason this is not an issue.
