### ISSUE TITLE
Vagante not updating since 38a

### ISSUE THREAD

**Issue by jnfrye** [ekunuke/vagante_issues#83]
My installation of Vagante has been stuck at 38a (which may have been when I installed it, actually). 
- I am running the Linux version
- I tried deleting local content and installing again, but still it's version 38a

Let me know if you need any more details.

**Comment by ekunuke** [comment]
We've recently run into an issue with our Mac/Linux builds which is causing a delay in their release. Apologies for the inconvenience.
