### ISSUE TITLE
Wildling Fists Lv.1 Punching goblins through walls

### ISSUE THREAD

**Issue by mishapsi** [ekunuke/vagante_issues#84]
Cornered a goblin and a mimic in a cubby hole like this:

```
0 X X X
@ G M X
X X X X
```

may have had heavy punches
punched Goblin through the wall next to Mimic

**Comment by ekunuke** [comment]
I think I fixed all issues with entities being pushed into levels, though more testing is needed

![betr_coll](https://cloud.githubusercontent.com/assets/1480644/14968843/ea694352-1073-11e6-8976-14adf058c7dd.png)

**Comment by ekunuke** [comment]
Found a bug with new code, reverting this fix until solved :(

**Comment by ekunuke** [comment]
Commited a new attempt to fix this to master, haven't found any cases where it breaks. More testing still needed
