### ISSUE TITLE
OMP Direct IP Connection

### ISSUE THREAD

**Issue by Darksiden** [ekunuke/vagante_issues#85]
I am not able to host or even connect to other players using Direct IP. It fails every time, I've checked ports, firewall blocking any connections, along with my routers firewall in case it was blocking incoming connections but it wasn't. At this point I was assuming it had to be my router denying incoming connections still so again I went and opened the router completely on my gateway IP (bypassing port forwarding and allowing all connections to come through my IP) but it still did not work. My friends are also having trouble with this. Is anyone else dealing with this issue?

**Comment by ekunuke** [comment]
It looks like this isn't just you, I'm looking into this further.

**Comment by ekunuke** [comment]
I believe this has been fixed for the next upcoming release (build 42). Some more testing is required to be sure though.
