### ISSUE TITLE
Goblin Boss Glitch/OMP Alchemist Glitch

### ISSUE THREAD

**Issue by RemediaV** [ekunuke/vagante_issues#90]
Hey, 
It's been a thing for a while now, so I thought I'd bring it up. If you freeze goblin boss right before or when he grabs you, you'll be fine, but as soon as the frozen frames are over you'll be teleported where ever you are back to goblin boss so he can finish throwing you lol. I've played this game on YouTube a lot now and I've captured it twice on video if you want to check them out:
Patch 33a Episode 16: https://youtu.be/W7TbKRwJZHo?t=5m7s
Patch 40c Episode 44: https://youtu.be/2ae_ihpg1LM?t=2m15s

Also once you get Chemical Transmutation as Alchemist mage your supposed to be able to combine two potions into another different one but it doesn't work properly in Online Multiplayer. I imagine it's known already but I thought I'd give a quick heads up. I also have this on video here:
Patch 37c Episode 29: https://youtu.be/-rV1jd5eFck?t=7m38s

Love the game so far despite how angry it may make me sometimes! Keep it up and thanks for making it!
-Justyn

**Comment by k6l2** [comment]
I've fixed the BossGoblin glitch, and creating a new issue for the OMP Chemical Transmutation bug.

In the future, please submit two separate issues instead of one issue with two bugs inside.
