### ISSUE TITLE
Minor 4th World Running Golem Glitch.

### ISSUE THREAD

**Issue by RemediaV** [ekunuke/vagante_issues#94]
Hey,
Recently I encountered a weird glitch with the Running Golem guys in the fourth world. Instead of jumping at me or coming straight down over me it just started flying diagonally into the distance. In the video it seems to happen when it hits the Smithy but I don't know for sure that's what caused it. At the time I just thought it was just that enemy being bullshit but after rewatching, its seems like a minor glitch.
I have the video here:
Patch 41d: https://youtu.be/2FQvkelV3EU?t=44m32s

**Comment by k6l2** [comment]
Thanks for submitting this video, I keep thinking I fixed this bug but I guess not lol...

**Comment by k6l2** [comment]
I made a fix for next release, but not 100% sure it fixes this issue.  I'll close it for now though.
