### ISSUE TITLE
Unable to proceed: Showstopping Map Design

### ISSUE THREAD

**Issue by Cheridan** [ekunuke/vagante_issues#96]
![20160506162213_1](https://cloud.githubusercontent.com/assets/3827314/15086619/a616008c-13a7-11e6-98b3-a05e69e18c2f.jpg)

I assume you're supposed to stand on the boulder that falls from the trap here in order to jump up to that area, but I had pushed it over into that lower area to cover up the spikes without realizing that it was necessary.

I couldn't move on to the next area so I had to just drown myself in a puddle.

**Comment by ekunuke** [comment]
Fixed for update 56
