### ISSUE TITLE
HP Doesn't Synch in OMP while in the leafy waiting room.

### ISSUE THREAD

**Issue by 1wolffan** [ekunuke/vagante_issues#97]
A friend and I decided to try some Online Multiplayer the other day. We found a couple bugs. I did a quick search to see if they had already been covered. This one had not.

When choosing Characters, the HP Display doesn't show the proper HP you'll have for the game. For example, he saw his character would have full HP and I would have the Multiplayer reduction. But mine would show me as having my full HP, but him having the multiplayer reduction.

As soon as we went through the door, we each saw our HP as it should be.

**Comment by ekunuke** [comment]
Fixed (will be live in next update).

**Comment by 1wolffan** [comment]
Thanks again for looking into these bugs for me. I'm just glad I could help you pinpoint them. :)
