### ISSUE TITLE
Can't see where the cursor is in OMP character select if you go beyond sprite choice.

### ISSUE THREAD

**Issue by 1wolffan** [ekunuke/vagante_issues#98]
A friend and I decided to try some Online Multiplayer the other day. We found a couple bugs. I did a quick search to see if they had already been covered. This one had not.

When selecting a character, if you move the cursor beyond the sprite selection option to the Backgrounds, you can't see where your cursor is anymore. I understand not allowing them in Muliplayer, but you should at least still be able to see where your cursor is down there, so you can move it back easily, if you'd like. The other option would be to dis-allow the cursor to move there in the first place; at least during OMP.

**Comment by ekunuke** [comment]
Fixed, thanks.
