### ISSUE TITLE
Shop Price bug - Items show as way more expensive than they should be.

### ISSUE THREAD

**Issue by 1wolffan** [ekunuke/vagante_issues#99]
A friend and I decided to try some Online Multiplayer the other day. We found a couple bugs. I did a quick search to see if they had already been covered. This one had not.

The shop prices seem to show as WAY more expensive than they actually are. For example, a potion or a scroll on Level 1 will be marked as 100 gold. You can't buy it if you don't have that much available. But when you do buy it on later levels (because who gets 100 in the first level?) it only takes about what a scroll or potion would cost (15 G-ish) I was unable to test whether this also applied to weapons and armor, because the regen potion, and uncurse scroll were higher priorities.

**Comment by k6l2** [comment]
Should be fixed after next release, let us know if something strange like this happens again.

**Comment by 1wolffan** [comment]
Will do. That's why I mentioned it.
